### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Alok",
  "email": "alokkk@gmail.com",
  "username": "alok",
  "password": "123456"
}

### Login User
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "alokkk@gmail.com",
  "password": "123456"
}
